support `@supports`
yesodweb/shakespeare pull request #263
Opened 2022-02-28 11:07 UTC by jeongoon

Hi, I'm trying to add @supports.
I made some test by referring `@media`.

but I don't know how to apply to my `curren` setup right away to see the effects as well.
because I'm not a professional programmer.
is there any way to apply in my `stack.yaml` or equivalent one to compile with patched version?

2022-03-01 07:12 UTC, jeongoon commented
I found how to compile yesod with patched shakespeare  [from stackoverflow](https://stackoverflow.com/questions/32849269/how-to-install-use-a-local-version-of-package-using-stack).
compiling now. hopefully work as I wanted.

2022-03-02 07:45 UTC, snoyberg commented
Have you had a chance to test this and see if it does what you're looking for?

2022-03-02 08:09 UTC, jeongoon commented
Oh, I'm using my patched version now (on archlinux with lts 16.31 which included in scaffolding) 
But i can see some test is failing here.
Any guide line to help?

2022-03-02 15:12 UTC, snoyberg requested changes

2022-03-02 15:12 UTC, snoyberg commented on test/Text/CssSpec.hs
> +      celper "@media only screen {foo bar{baz:bin}}" [lucius|
I'd prefer not to see unrelated changes in this PR. This line specifically is present to test that things work both with and without extra spacing.

2022-03-03 04:52 UTC, jeongoon commented
noted. I revert my changes which is note related to "@supports".
thank you.

2022-03-04 05:17 UTC, merged